### ISSUE TITLE
main:670: number of platforms : error -1001

### ISSUE THREAD

**Issue by darakian** [Oblomov/clinfo#11]
Using an intel ivy bridge laptop I get the following when I run clinfo.
main:670: number of platforms : error -1001
Not sure if that's expected or not, but I think this chip supports opencl.

**Comment by Oblomov** [comment]
The error indicates you have no OpenCL platforms installed. Also, it would seem you are either using a much older version of this clinfo, or a different clinfo, since in case of no platforms this clinfo simply reports `Number of platforms: 0`.

If you believe you are indeed using the latest version of this clinfo, please reopen the issue providing the output of `clinfo --version`.

**Comment by darakian** [comment]
You're right. I did not have an opencl runtime installed. Perhaps you could print a suggestion in the error message? Thanks for the program :)

**Comment by Oblomov** [comment]
As I said, when there are no ICD my clinfo doesn't output that error anymore; instead, it says that there are no OpenCL platforms. If you are seeing that error you're either using a very old version or not using this clinfo, but some other implementation.

**Comment by darakian** [comment]
Gotcha thanks. This was the fedora 21 repo package so it probably is very out of date.

**Comment by UniqueFool** [comment]
given that this clinfo is different from the stock version shipped with ubuntu, it may make sense to add some kind of marker/notice to the help/version string, so that people can more easily tell if they are using the correct version

**Comment by Oblomov** [comment]
IIRC, the clinfo shipped in older distributions doesn't even respond to `--version` or `--help` (been a while since I last used it). I think that's enough of a way to differentiate ;-)

More seriously I can't explicitly say “not the Ubuntu one” or “not the Fedora one” because I actually think mine is the one getting adopted (I know for sure that Debian is picking it up now.)

**Comment by UniqueFool** [comment]
which is great, it is so much better, and provides tons of additional info, too
