### ISSUE TITLE
detection of ICD/OpenCL issues

### ISSUE THREAD

**Issue by UniqueFool** [Oblomov/clinfo#14]
I am finding clinfo to be remarkably tolerant, even with missing/mismatching ICDs installed, for instance, nvidia drivers older than 352 do not provide support for OpenCL 1.2, which will cause linking errors when building corresponding code:

https://bugs.launchpad.net/enblend/+bug/1305794
http://stackoverflow.com/a/15866165
http://stackoverflow.com/a/19520687
https://github.com/code-iai/iai_kinect2/issues/13

So it may be helpful to specifically look for such issues and show some kind of warning when running clinfo

**Comment by Oblomov** [comment]
This is an interesting idea, but it's not trivial to implement. The problem is that there is no (official) way to find which version of OpenCL is supported by the ICD loader (libOpenCL) —the exception being `ocl-icd`, which provides its own extension to query for the supported profile. Without that, the only way to check for the supported version would be to try and actuallly call a higher-version function, trapping segmentation faults. Not exactly robust …

**Comment by Oblomov** [comment]
This is now implemented in the latest master branch. Heuristics for OpenCL version support by the ICD loader can be improved, but those may be opened as separate enhancement requests.

**Comment by UniqueFool** [comment]
> the only way to check for the supported version would be to try and actuallly call a higher-version function, trapping segmentation faults. Not exactly robust …

haven't looked at your code yet, but would those DSO pointers not be NULL (invalid) if unsupported ?

**Comment by Oblomov** [comment]
Yes, that's exactly the way I've implemented it in the code: I do a `dlsym` of a later function and try to guess the supported version from that.

**Comment by UniqueFool** [comment]
ok, thanks for clarifying that - I will be testing this with different platforms and report back here.
Thanks also for being so responsive, much appreciated !

**Comment by UniqueFool** [comment]
BTW: This may also be helpful to provide even better runtime information, it's a collection of kernels that are known to crash different platforms: https://github.com/eholk/opencl-stress
