### ISSUE TITLE
clinfo FPGA

### ISSUE THREAD

**Issue by mohmsslk** [Oblomov/clinfo#18]
Hello, 
I want to list my FPGA in clinfo, but I dont know how to run your code or to install it, could you show me how please?
Thnak you

**Comment by Oblomov** [comment]
[Clone the repository](https://help.github.com/articles/cloning-a-repository/), change to the resulting working directory, run `make` in it.You need to have development packages for OpenCL installled (depends on your operating system and distribution).

If you are on Windows, you're a bit out of luck since the Makefile won't work out of the box and I do not have a development machine where I can twiddle around to fix it.
